defaults: &defaults
  proctor:
    api_host: "http://old.api/"
    like:
      Comment: "/comment/%s"
      Favorite: "/favorite/%s"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
